version: "3.8"
services:
  whisper:
    container_name: backend-api
    build:
      context: .
      dockerfile: Dockerfile
    # image:
    platform: linux/amd64
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/code
      - whisper-volume:/whisper-volume

volumes:
    whisper-volume:
      external: true


